services:
  flagfrenzy-sveltekit:
    build:
      context: ./flagfrenzy-sveltekit
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - webapp_net
    volumes:
      - ./flagfrenzy-sveltekit:/app
      - /app/node_modules

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - webapp_net
    volumes:
      - mysql-data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE_PORT: ${MYSQL_PORT}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  api:
    build: 
      context: ./API
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    networks:
      - webapp_net
    volumes:
      - ./API/src:/app
    env_file: .env
    environment:
      ALLOWED_HOSTS: "*"
    working_dir: "/app"
    command: >
      sh -c "sleep 10 && uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webapp_net
    depends_on:
      - flagfrenzy-sveltekit

volumes:
  mysql-data:

networks:
  webapp_net:
